spring:
  application:
    name: email-sender
  mail:
    host: ${mail-host:localhost}
    port: ${mail-port:25}
    properties:
      mail:
        smtp:
          auth: ${mail-smtp-auth:false}
          starttls:
            enable: ${mail-smtp-starttls-enable:false}


app:
  gmail:
    username: ${gmail-username}
    password: ${gmail-password}
    host: ${gmail-host:smtp.gmail.com}
    port: ${gmail-port:587}
  dkim:
    enabled: ${dkim-enabled:false}
    private-key-path: ${dkim-private-key}
    selector: ${dkim-selector}
    domain: ${dkim-domain}
    body-canonicalization: ${dkim-body-canonicalization:simple}
    header-canonicalization: ${dkim-header-canonicalization:simple}
